name: Grove Of Titans Cover
favicon: null
layout_spectrum: 0.9965655552223325
typography_spectrum: 0.06682060426101089
title: Vision
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffefc'
    - '#1a1732'
    - '#93859c'
    - '#62546b'
    - '#f0cbed'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
