name: Grove Of Titans Cover
favicon: null
layout_spectrum: 1
typography_spectrum: 0.00744
title: Vision
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080f2d'
    - '#76655e'
    - '#4b2e30'
    - '#0c3624'
    - '#81aa58'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 1
  rhythmicContrast: 0
purpose: []
